### ISSUE TITLE
VM144:1 GET http://localhost:3000/api/me 401 (Unauthorized)

### ISSUE THREAD

**Issue by b2times4** [sandrinodimattia/nextjs-auth0-example#1] opened 2019-09-20 12:10 UTC
First off : this is just fan-tastic. Thanks so much for the work.

In the effort of making this absolutely perfect I just wanted to mention the (logical) error (**only in the console**) you get after:
1) cloning the repo
2) setting up Auth0 app
3) adding the config vars for Auth
4) starting up the app

Immediately after that (not even interacting with the app) you get an error (only in console so nothing that breaks the app) stating:
**GET http://localhost:3000/api/me 401 (Unauthorized)**
Should probably try / catch that

**Comment by sandrinodimattia** [comment] 2019-09-23 13:35
Hi @b2times4 thanks for the feedback. The error you see is by design. When the home page loads it will call the `/api/me` endpoint to try and fetch the user from the client side. If it fails, we know on the client side that the user is not logged in (and we can use this to render a "Sign In" button).

If the call succeeds, we know the user is logged in and we can render the user profile (+ show the logout button):

![image](https://user-images.githubusercontent.com/655409/65430194-d1623880-de17-11e9-93d7-1f81ac140485.png)

Let me know if that helps and if you're ok to close the issue.

**Closed as completed** 2019-10-10 09:22 UTC
